# Change these first
owner: martec # Your GitHub organization or username, where this repository lives
repo: alfa-status # The name of this repository
user-agent: martec 

assignees: # Users to assign downtime issues (optional)
  - martec

sites:
  - name: Anime Fórum
    url: https://anime-forum.info
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.anime-forum.info
  name: Anime-Fórum Status Site
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/martec/alfa-status/master/assets/alfalogo.png
  favicon: https://raw.githubusercontent.com/martec/alfa-status/master/assets/favicon.ico
  introTitle: Últimos status
  introMessage: Site para anunciar qualquer manutenção e o status atual do Anime-Fórum
  navbar:
    - title: Home
      href: https://anime-forum.info
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO/issues
  theme: night

commitMessages:
  commitAuthorName: "alfa Bot"
  commitAuthorEmail: "admin@anime-forum.info"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
